/**
 * WasmLoader.ts
 *
 * Utility for securely fetching WASM modules with Subresource Integrity (SRI)
 * checks to prevent supply chain tampering.
 *
 * Build-time hashes are generated by `build/generate-sri-hashes.mjs` and
 * written to `public/wasm-hashes.json`.  At runtime this module fetches the
 * manifest, computes a SHA-384 digest of the downloaded bytes, and compares
 * the two values before the WASM module is instantiated.
 *
 * If the digest does not match the module is **never instantiated** and a
 * `SRIIntegrityError` is thrown so that calling code / the UI can surface a
 * clear tamper-warning rather than silently executing compromised code.
 * Register a global fail-safe handler with `onSRIViolation()`.
 */

export interface WasmHashesManifest {
  generated: string;
  algorithm: string;
  assets: Record<string, string>;
}

export interface WasmLoaderOptions {
  manifestUrl?: string;
  bypassVerification?: boolean;
}

export class SRIIntegrityError extends Error {
  readonly url: string;
  readonly expected: string;
  readonly actual: string;

  constructor(url: string, expected: string, actual: string) {
    super(
      `[SRI] Integrity check FAILED for "${url}".\n` +
        `  Expected: ${expected}\n` +
        `  Received: ${actual}\n` +
        `  Aborting load — resource may have been tampered with.`
    );
    this.name = "SRIIntegrityError";
    this.url = url;
    this.expected = expected;
    this.actual = actual;
    Object.setPrototypeOf(this, SRIIntegrityError.prototype);
  }
}

let _manifestCache: WasmHashesManifest | null = null;
let _manifestUrl = "/wasm-hashes.json";

export async function loadWasmManifest(
  manifestUrl: string = "/wasm-hashes.json"
): Promise<WasmHashesManifest | null> {
  if (_manifestCache && manifestUrl === _manifestUrl) {
    return _manifestCache;
  }

  _manifestUrl = manifestUrl;

  try {
    const res = await fetch(manifestUrl, { cache: "no-store" });
    if (!res.ok) {
      console.warn(
        `[SRI] Could not load manifest from ${manifestUrl} (HTTP ${res.status}). ` +
          `Running without integrity verification.`
      );
      return null;
    }
    _manifestCache = (await res.json()) as WasmHashesManifest;
    return _manifestCache;
  } catch (err) {
    console.warn(
      `[SRI] Failed to fetch manifest: ${(err as Error).message}. ` +
        `Running without integrity verification.`
    );
    return null;
  }
}

export function clearWasmManifestCache(): void {
  _manifestCache = null;
}

// ─── Fail-safe UI helpers ─────────────────────────────────────────────────────

/**
 * Global callback invoked whenever an SRI mismatch is detected.
 *
 * Wire up your application's critical-error modal / toast in the bootstrap:
 *
 * ```ts
 * import { onSRIViolation } from "@/utils/WasmLoader";
 * onSRIViolation((err) => {
 *   showCriticalErrorModal({
 *     title: "Security Warning — WASM Integrity Failure",
 *     message: err.message,
 *   });
 * });
 * ```
 */
let _sriViolationHandler: ((err: SRIIntegrityError) => void) | null = null;

export function onSRIViolation(
  handler: (err: SRIIntegrityError) => void
): void {
  _sriViolationHandler = handler;
}

function fireSRIViolation(err: SRIIntegrityError): void {
  // Always log to the browser console in a visually prominent way.
  console.error(
    "%c[SRI INTEGRITY VIOLATION]%c\n" + err.message,
    "color: red; font-weight: bold; font-size: 1.1em;",
    "color: inherit;"
  );
  _sriViolationHandler?.(err);
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

async function computeSHA384Base64(buffer: ArrayBuffer): Promise<string> {
  const hashBuffer = await crypto.subtle.digest("SHA-384", buffer);
  const bytes = new Uint8Array(hashBuffer);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

export async function fetchSecureWasm(
  url: string,
  options: WasmLoaderOptions = {}
): Promise<ArrayBuffer> {
  const { manifestUrl = "/wasm-hashes.json", bypassVerification = false } =
    options;

  const response = await fetch(url, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(
      `[SRI] Failed to fetch "${url}": HTTP ${response.status} ${response.statusText}`
    );
  }

  const buffer = await response.arrayBuffer();

  if (bypassVerification) {
    console.warn(
      `[SRI] Integrity verification BYPASSED for "${url}". Do not use in production.`
    );
    return buffer;
  }

  const manifest = await loadWasmManifest(manifestUrl);

  if (!manifest) {
    console.warn(
      `[SRI] No manifest available. Returning "${url}" unverified. ` +
        `Run build hash generation to include integrity checks.`
    );
    return buffer;
  }

  let urlKey: string;
  try {
    urlKey = new URL(url, "https://localhost").pathname;
  } catch {
    urlKey = url;
  }

  const expectedSRI = manifest.assets[urlKey];

  if (!expectedSRI) {
    console.warn(
      `[SRI] No manifest entry for "${urlKey}". Returning bytes unverified.`
    );
    return buffer;
  }

  const actualBase64 = await computeSHA384Base64(buffer);
  const actualSRI = `sha384-${actualBase64}`;

  if (actualSRI !== expectedSRI) {
    const err = new SRIIntegrityError(url, expectedSRI, actualSRI);
    fireSRIViolation(err);
    throw err;
  }

  return buffer;
}

export async function secureLoadWorker(
  url: string,
  options: WasmLoaderOptions = {}
): Promise<string> {
  const buffer = await fetchSecureWasm(url, options);
  const blob = new Blob([buffer], { type: "application/javascript" });
  return URL.createObjectURL(blob);
}

/**
 * Convenience wrapper: fetches and instantiates a WASM module in one call.
 *
 * The module is **never instantiated** if the SRI check fails — a
 * `SRIIntegrityError` is thrown and the fail-safe UI handler is invoked.
 */
export async function instantiateSecureWasm(
  url: string,
  importObject: WebAssembly.Imports = {},
  options: WasmLoaderOptions = {}
): Promise<WebAssembly.WebAssemblyInstantiatedSource> {
  const buffer = await fetchSecureWasm(url, options);
  return WebAssembly.instantiate(buffer, importObject);
}
