import { defineConfig } from "vitest/config";
import path from "node:path";
import { fileURLToPath } from "node:url";

const configDir = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  esbuild: {
    jsx: "automatic",
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "tests/**/*.{test,spec}.{ts,tsx}",
    ],
    exclude: ["tests/e2e/**"],
    coverage: {
      provider: "v8",
      include: ["src/lib/**", "src/utils/**"],
      exclude: [
        "src/lib/testing/**",
        "src/**/*.d.ts",
        // Untested files/folders
        "src/lib/compilationWorker.ts",
        "src/lib/contractInstantiator.ts",
        "src/lib/criterionParser.ts",
        "src/lib/definitionProvider.ts",
        "src/lib/feeDataService.ts",
        "src/lib/file-drop.ts",
        "src/lib/gasProfiler.ts",
        "src/lib/git.ts",
        "src/lib/githubImporter.ts",
        "src/lib/i18n.ts",
        "src/lib/integrationTestDiscovery.ts",
        "src/lib/invokeUtils.ts",
        "src/lib/liveShareService.ts",
        "src/lib/mathSafetyAnalyzer.ts",
        "src/lib/postBuildHookRunner.ts",
        "src/lib/referenceProvider.ts",
        "src/lib/rpcService.ts",
        "src/lib/rustHoverProvider.ts",
        "src/lib/rustTestParser.ts",
        "src/lib/scvalTransformer.ts",
        "src/lib/semanticTokensProvider.ts",
        "src/lib/sorobanRpc.ts",
        "src/lib/symbolIndexer.ts",
        "src/lib/templateRegistry.ts",
        "src/lib/wasmDiscovery.ts",
        "src/lib/audit/contractUpgradeabilityChecker.ts",
        "src/lib/auth/**",
        "src/lib/cloud/**",
        "src/lib/debug/**",
        "src/lib/diagnostics/**",
        "src/lib/identity/**",
        "src/lib/layout/**",
        "src/lib/plugins/**",
        "src/lib/security/**",
        "src/lib/stellar/FeeEstimator.ts",
        "src/lib/stellar/FeeSimulator.ts",
        "src/lib/stellar/SponsorshipPolicy.ts",
        "src/lib/test/**",
        "src/lib/tutorials/**",
        "src/lib/vcs/blameService.ts",
        "src/lib/vcs/githubAuth.ts",
        "src/lib/vcs/gitHistoryService.ts",
        "src/lib/vcs/revertUtility.ts",
        "src/lib/vcs/sshKeyManager.ts",
        "src/lib/vcs/stagingService.ts",
        "src/lib/vcs/stashService.ts",
        "src/lib/vcs/treeCalculator.ts",
        "src/lib/wallet/AlbedoAdapter.ts",
        "src/lib/wallet/FreighterAdapter.ts",
        "src/lib/wallet/HanaAdapter.ts",
        "src/lib/wallet/index.ts",
        "src/utils/WorkerResourceMonitor.ts",
        "src/utils/XdrValidator.ts",
        "src/utils/eventSubscriber.ts",
        "src/utils/explorerLinks.ts",
        "src/utils/exportZip.ts",
        "src/utils/freighter.ts",
        "src/utils/friendbot.ts",
        "src/utils/offlineQueue.ts",
        "src/utils/parseProptestOutput.ts",
        "src/utils/proptestSnippets.ts",
        "src/utils/registerServiceWorker.ts",
        "src/utils/wasmDiff.ts",
        "src/utils/WasmLoader.ts",
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 70,
        statements: 80,
      },
      reporter: ["text", "lcov", "html"],
    },
  },
  resolve: {
    alias: { "@": path.join(configDir, "src") },
  },
});
